import Link from "next/link"
import Image from "next/image"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function AboutPage() {
  const teamMembers = [
    {
      name: "Denis Setiawan",
      role: "CEO & Co-Founder",
      bio: "Product manager with over +1 years experience in several startup focusing on digitalization and scalability.",
      avatar: "/CEO-image.jpg",
    },
    {
      name: "Eric Julianto",
      role: "CTO & Co-Founder",
      bio: "AI researcher with expertise in natural language processing and educational technology.",
      avatar: "/CTO-image.jpeg",
    },
    {
      name: "Marcus Williams",
      role: "Chief Learning Officer",
      bio: "Former university professor with 15 years of experience in curriculum development.",
      avatar: "/placeholder.svg?height=300&width=300",
    },
    {
      name: "Priya Patel",
      role: "Head of Product",
      bio: "Product leader with experience building educational platforms used by millions.",
      avatar: "/placeholder.svg?height=300&width=300",
    },
  ]

  return (
    <div className="min-h-screen">
      <div className="container mx-auto px-4 py-16">
        <Button variant="ghost" asChild className="mb-8">
          <Link href="/" className="flex items-center gap-2">
            <ArrowLeft className="h-4 w-4" /> Back to Home
          </Link>
        </Button>

        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl md:text-5xl font-bold mb-6">About Our Company</h1>

          <div className="prose dark:prose-invert max-w-none mb-16">
            <p className="text-xl text-zinc-600 dark:text-zinc-400 mb-6">
              We're on a mission to revolutionize education by making personalized learning accessible to everyone.
            </p>

            <h2>Our Story</h2>
            <p>
              Founded in 2023, our company was born from a simple observation: traditional learning resources often
              follow a one-size-fits-all approach that doesn't account for individual learning styles, backgrounds, or
              goals.
            </p>
            <p>
              Our founders, Alex and Sophia, experienced this problem firsthand in their careers in education and AI
              research. They envisioned a platform that could leverage the latest advances in artificial intelligence to
              create truly personalized learning experiences.
            </p>

            <h2>Our Mission</h2>
            <p>
              We believe that everyone deserves access to high-quality, personalized education that adapts to their
              unique needs. Our mission is to democratize education by using AI to create customized learning paths for
              any subject, making it easier for people to acquire new skills and knowledge efficiently.
            </p>

            <h2>Our Technology</h2>
            <p>
              Our platform is powered by state-of-the-art large language models that have been fine-tuned specifically
              for educational content generation. We've developed proprietary algorithms that analyze learning sequences
              and optimize them for knowledge retention and engagement.
            </p>
            <p>
              All content generated by our AI is reviewed by subject matter experts to ensure accuracy and quality,
              combining the efficiency of artificial intelligence with human expertise.
            </p>
          </div>

          <h2 className="text-2xl md:text-3xl font-bold mb-8">Our Team</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
            {teamMembers.map((member, index) => (
              <div key={index} className="flex flex-col md:flex-row gap-6 items-start">
                <div className="relative w-24 h-24 rounded-full overflow-hidden flex-shrink-0">
                  <Image src={member.avatar || "/CEO-image.jpg"} alt={member.name} fill className="object-cover" />
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-1">{member.name}</h3>
                  <p className="text-emerald-600 dark:text-emerald-400 mb-2">{member.role}</p>
                  <p className="text-zinc-600 dark:text-zinc-400">{member.bio}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="bg-zinc-50 dark:bg-zinc-800 p-8 rounded-xl">
            <h2 className="text-2xl font-bold mb-4">Join Our Journey</h2>
            <p className="text-zinc-600 dark:text-zinc-400 mb-6">
              We're always looking for talented individuals who are passionate about education and technology. Check out
              our careers page to see current openings.
            </p>
            <Button asChild>
              <Link href="/careers">View Open Positions</Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
